### ISSUE TITLE
a86: Check immediate ranges

### ISSUE THREAD

**Issue by dvanhorn** [cmsc430/www#115]
Instructions that take immediate values should check that values are in range.  Some instructions, e.g. `Cmp` can only take 32-bit immediate, and will silently do something unexpected if you use a 64-bit immediate.

**Comment by pdarragh** [comment]
Regardless of whether we move to the OO technique in #113, I've been planning to revise how instruction AST nodes are defined to make things like this easier to specify, so I'm not sure whether we ought to do it right now in the main branch or not.

**Comment by laelath** [comment]
I think this is orthogonal to that, since these are just checks on the target language AST

**Comment by dvanhorn** [comment]
I've added checks in a branch which we can merge later.  (Probably after the exam is fine.)  I haven't done the "if moving into memory you only get 32-bits" part yet.

**Comment by dvanhorn** [comment]
Just remembered you can't move immediates into memory, so I think this is done now.
